### ISSUE TITLE
About new pages

### ISSUE THREAD

**Issue by xxcn8423** [hemangsk/DevJournal#1]
Hi, I like your theme a lot. 
I just want to know, did you notice that, there are three blank navigators in your navigation bar. And whenever I want to create a new page, it goes after them, How to deal with that? Thank you

**Comment by hemangsk** [comment]
Hey @xxcn8423 ! Thanks for getting in touch and I'm really happy that you liked the theme! 😃 👍 

Would you mind sharing a screenshot because I'm unable to figure out the blank navigator thing.

**Comment by hemangsk** [comment]
@xxcn8423 Hey! I have found the issue, working on it. I will reply here as soon as it is resolved 👍

**Comment by hemangsk** [comment]
Issue resolved in both the master and gh-pages branch, so you can pull the changes or fork again. Anything.
The bug was that it was looping through all the pages... but we wanted it to loop only through the pages which are actually pages and had a title. 
So modified the header.html file,

```
<ul class="nav navbar-nav">
        {% for page in site.pages %}
        {% if page.title %}
        <li><a href="{{page.permalink | prepend: site.baseurl }}">{{page.title}}</a></li>
        {% endif  %}
        {% endfor %}
 </ul>
```

Thanks a lot ! 👍  😄
